### ISSUE TITLE
feat: Ultilize `free_gpu_memory_fraction` to control max VRAM consumption

### ISSUE THREAD

**Issue by hiro-v** [janhq/nitro-tensorrt-llm#25]
Currently, tensorrt_llm with tries to allocate as much as possible the VRAM consumption with 3 portions: https://nvidia.github.io/TensorRT-LLM/memory.html

Please add `free_gpu_memory_fraction` - https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/runtime/model_runner_cpp.py#L169-L172 as nitro parameter so that we can control it (of course the machine has to have enough VRAM for weight loading but we can reduce VRAM for other portions.

This would let more people with GPU VRAM constraint be able to use tensorrt_llm

**Comment by tikikun** [comment]
<img width="728" alt="image" src="https://github.com/janhq/nitro-tensorrt-llm/assets/22268502/d867b4a1-ddf0-4c3b-a5e1-3d2190983169">

Relevant document
![Uploading image.png…]()
