### ISSUE TITLE
feat: TensorRT-LLM Support for logits_prob

### ISSUE THREAD

**Issue by hiro-v** [janhq/nitro-tensorrt-llm#54]
Hi there, 

Currently I'm using cortex.tensorrt-llm in order to benchmark for MMLU and TruthfulQA using https://github.com/EleutherAI/lm-evaluation-harness/tree/main

However, the current API does not return `logits_prob`

Please add `logits_prob` in `chat_completion` API as it's supported from 0.8.0 `https://github.com/NVIDIA/TensorRT-LLM/issues/983`

Thank you

**Comment by gabrielle-ong** [comment]
Closing all open Tensorrt-llm stories due to TensorRT-LLM not supporting Desktop
Parent issue: https://github.com/janhq/cortex.cpp/issues/1742
