### ISSUE TITLE
feat: tensorrt-llm-engine README.md file

### ISSUE THREAD

**Issue by irfanpena** [janhq/nitro-tensorrt-llm#55]
Problem
We don''t have a proper cortex.tensorrt-llm README file

Success Criteria
Clear and concise documentation of the cortex.tensorrt-llm README.md file that includes quickstart, build from source section

**Comment by gabrielle-ong** [comment]
Closing all open Tensorrt-llm stories due to TensorRT-LLM not supporting Desktop
Parent issue: https://github.com/janhq/cortex.cpp/issues/1742
